In [2]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [9]:
W = np.array([[1, 2, 3], 
              [4, 5, 6]])
W.shape

(2, 3)

In [6]:
W.ndim

2

In [8]:
W = np.array([[1, 2, 3], 
              [4, 5, 6]])
X = np.array([[0, 1, 2], 
              [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [10]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [11]:
A = np.array([[1, 2],
              [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [12]:
A = np.array([[1, 2],
              [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

In [14]:
# 벡터의 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [15]:
# 행렬의 곱
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [16]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [19]:
import numpy as np
W1 = np.random.randn(2, 4) # 가중치
b1 = np.random.randn(4) # 편향
x = np.random.randn(10, 2) # 입력
h = np.matmul(x, W1) + b1

In [20]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [21]:
a = sigmoid(h)

In [22]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

In [23]:
a = ['A', 'B']
a += ['C', 'D']
a

['A', 'B', 'C', 'D']

In [7]:
import numpy as np
D, N = 8, 7
x = np.random.randn(1, D) # 입력
y = np.repeat(x, N, axis=0) # 순전파
dy = np.random.randn(N, D) # 무작위 기울
dx = np.sum(dy, axis=0, keepdims=True) # 역전파

In [13]:
import numpy as np
D, N = 8, 7
x = np.random.randn(N, D) # 입력
y = np.sum(x, axis=0, keepdims=True) # 순전파

dy = np.random.randn(1, D) # 무작위 기울기
dx = np.repeat(dy, N, axis=0) # 역전파

In [15]:
import numpy as np
a = np.random.randn(3)
a.dtype

dtype('float64')

In [16]:
b = np.random.randn(3).astype(np.float32)
b.dtype

dtype('float32')

In [17]:
c = np.random.randn(3).astype('f')
c.dtype

dtype('float32')

In [19]:
import cupy as cp
x = cp.arange(6).reshape(2, 3).astype('f')
x

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [20]:
x.sum(axis=1)

array([ 3., 12.], dtype=float32)