In [1]:
text = 'You say goodbye and I say hello.'

In [2]:
text = text.lower()
text = text.replace('.', ' .')
text

'you say goodbye and i say hello .'

In [3]:
words = text.split(' ')
words

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']

In [4]:
word_to_id = {}
id_to_word = {}

for word in words:
    if word not in word_to_id:
        new_id = len(word_to_id)
        word_to_id[word] = new_id
        id_to_word[new_id] = word

In [5]:
id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}

In [6]:
word_to_id

{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}

In [7]:
id_to_word[1]

'say'

In [8]:
word_to_id['hello']

5

In [9]:
import numpy as np
corpus = [ word_to_id[w] for w in words ]
corpus = np.array(corpus)
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

In [10]:
import sys
sys.path.append('..')
from common.util import preprocess

text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)

In [11]:
print(corpus)

[0 1 2 3 4 1 5 6]


In [12]:
print(id_to_word)

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [13]:
C = np.array([
    [0, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 0]
], dtype=np.int32)

In [14]:
print(C[0]) # ID가 0인 단어의 벡터 표현

[0 1 0 0 0 0 0]


In [15]:
print(C[4]) # ID가 4인 단어의 벡터 표현

[0 1 0 1 0 0 0]


In [16]:
print(C[word_to_id['goodbye']]) # "goodbye"의 벡터 표현

[0 1 0 1 0 0 0]


In [17]:
word_to_id['goodbye']

2

In [22]:
from common.util import create_co_matrix, ppmi

C = create_co_matrix(corpus, len(word_to_id), window_size=1)
W = ppmi(C)

In [25]:
U, S, V = np.linalg.svd(W)

In [26]:
print(U[0, :2])

[3.40948752e-01 5.55111512e-16]
